spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkrecipes?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: KrystianKaz
    password: kkrecipes
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    schemas: kkrecipes
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:file:.env[.properties]
server:
  error:
    whitelabel:
      enabled: false

kkrecipes:
  apiKeyValue: ${API_KEY}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    schemas: ${DB_FLYWAY_SCHEMA}
  jpa:
    hibernate:
      ddl-auto: validate
server:
  error:
    whitelabel:
      enabled: false

kkrecipes:
  apiKeyValue: ${API_KEY_VALUE}