spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkrecipes?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: KrystianKaz
    password: kkrecipes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect